# config.yaml
system:
  version: "1.1.0"
  debug_mode: true

monitoring:
  # Lista de carpetas que quieres vigilar 
  directories:
    - "./test_folder"
  
  # Archivo de logs a analizar
  log_file: "server_logs.txt"

admin_password_hash: ""

database:
  name: "basilisk.db"

alerts:
  telegram:
    enabled: true
    token: ""     
    chat_id: "" 

network:
  whitelist:
    - ""

security:
  active_response: false # Solo avisa
  admin_password_hash: ""